### ISSUE TITLE
Determine the usage of a package by version.

### ISSUE THREAD

**Issue by jdalton** [anvaka/npmrank#6]
Based on https://twitter.com/davemethvin/status/638460262270566400

> Is there an easy way to determine which versions of your npm package the world is using? Like a pie chart of version share.

\cc @dmethvin

**Comment by anvaka** [comment]
@jdalton @dmethvin - I've added utility to count versions. 

Here is a public gist generate a moment ago for jquery and lodash: https://gist.github.com/anvaka/932a9395790d6c181ac3

To count which versions depend on your package use `countVersions.js` utility:

```
node countVersions.js jquery
```

If you pass `--print-names` it will show real packages instead of numbers:

```
node countVersions.js jquery --print-names
```

**Comment by jdalton** [comment]
:clap:

**Comment by dmethvin** [comment]
Awesome! :star2: :cake:
